### ISSUE TITLE
Configuration page results in 404

### ISSUE THREAD

**Issue by m-o-n-k** [ZIMK/Redmine-AutoWatch#7]
I'm using this plugin with following redmine environment:

<pre>
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  autowatch                      0.1.0
  line_numbers                   1.0.0
  redmine_agile                  1.3.12
  redmine_base_deface            0.0.1
  redmine_base_rspec             0.0.3
  redmine_checklists             3.0.2
  redmine_custom_workflows       0.0.4
  redmine_default_assign         0.4
  redmine_didyoumean             1.2.0
  redmine_dmsf                   1.4.9 stable
  redmine_doc_pu                 0.0.2
  redmine_embedded_video         0.0.3.1
  redmine_emojibutton            0.3.0
  redmine_equipment_status_viewer 1.0.1
  redmine_impasse                1.3.0
  redmine_information            1.0.2
  redmine_issue_templates        0.0.9
  redmine_knowledgebase          3.0.7
  redmine_lightbox2              0.1.3
  redmine_maintenance_mode       2.0.1
  redmine_mentions               0.0.1
  redmine_my_page_queries        2.1.6
  redmine_people                 0.1.6
  redmine_subtasks_inherited_fields 0.0.3
  redmine_sudo                   0.0.1
  redmine_tags                   2.3.0
  redmine_watcher_groups         0.0.1
  redmine_wiki_backlinks         0.0.2
  redmine_wiki_extensions        0.6.5
  redmine_wiki_issue_fields      0.4.1
  redmine_wiki_template          0.0.1
  wiki_external_filter           0.0.2
</pre>

When I try to visit the configuration page within the Redmine plugin administration page I only get a 404 error.

**Comment by adi-david** [comment]
Maybe you didn't change the plugin's folder name to "AutoWatch" (instead of "Redmine-AutoWatch")?

**Comment by cmich** [comment]
@m-o-n-k Could you provide further information from your error logs, please? The folder of the plugin has to be named "autowatch", as the [installation manual](https://github.com/ZIMK/Redmine-AutoWatch/blob/master/INSTALL.rdoc) specifies.

**Comment by m-o-n-k** [comment]
Wow I didn't see this coming. Guess I didn't read the installation manual carefully enough. My sorry bro. Works now. Thanks.
